spring:
  application:
    name: draw-server
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  redis:
    host: 118.67.129.198
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    db: 0

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful

auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expire-ms: 3600000
    refresh-token-expire-ms: 1209600000

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

kakao:
  auth:
    client-secret: ${KAKAO_CLIENT_SECRET}
    js-key: ${KAKAO_JS_KEY}
    rest-api-key: ${KAKAO_REST_API_KEY}
    callback-url: https://draw-nexters.netlify.app/callback/kakao

apple:
  auth:
    team-id: ${APPLE_TEAM_ID}
    aud: https://appleid.apple.com

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}

firebase:
  fmc:
    credential: ${FIREBASE_FCM_CREDENTIAL}
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  redis:
    host: 118.67.129.198
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    db: 3

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful

sentry:
  dsn: ${SENTRY_DSN}

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}
